namespace:
  name: secure-k8s-tenant

serviceAccount:
  name: secure-k8s-sa

tenant: "tenant-A"

deployment:
  name: secure-k8s-deployment
  replicas: 1
  image:
    repository: nginxinc/nginx-unprivileged
    tag: "1.23.3"
    pullPolicy: IfNotPresent
  containerPort: 8080
  resources:
    requests:
      cpu: "250m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  securityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  livenessProbe:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000
