{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-and-egress
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.networkPolicy.allowIngress }}
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.deployment.containerPort }}
  {{- end }}
  {{- if .Values.networkPolicy.allowSQS }}
  egress:
    - to:
        - ipBlock:
            cidr: {{ .Values.networkPolicy.sqsCidr }}
      ports:
        - protocol: TCP
          port: 443
  {{- end }}
{{- end }}
