{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
{{- end }}
