name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubeaudit
        run: |
          curl -sSL https://github.com/control-plane/kubeaudit/releases/latest/download/kubeaudit-linux-amd64 -o kubeaudit
          chmod +x kubeaudit
          sudo mv kubeaudit /usr/local/bin/

      - name: Run kubeaudit
        run: kubeaudit all -k ./

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "./"

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: "./"

      - name: Install Helm
        run: |
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Run Helm Lint
        run: helm lint .

      - name: Run Helm Template Render Check
        run: helm template my-secure-app .

      - name: Run Helm Dry-Run Install
        run: helm install my-secure-app . --dry-run --debug
